---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openweather-service
  labels:
    app: openweather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openweather-service
  template:
    metadata:
      labels:
        app: openweather-service
    spec:
      containers:
        - name: openweather-service
          image: matthausen/openweather-service:latest
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: smarthome-secrets
                  key: openweather-api-key
            - name: CITY
              valueFrom:
                secretKeyRef:
                  name: smarthome-secrets
                  key: city
---
apiVersion: v1
kind: Service
metadata:
  name: openweather-svc
spec:
  type: ClusterIP
  selector:
    app: openweather-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080