apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarthome-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-svc
            port:
              number: 80

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: openweather-svc
            port:
              number: 8080
