FROM nginx:stable-alpine
COPY build/ /usr/share/nginx/html 

# FROM node:14.17.4-alpine

# WORKDIR /app

# ENV PATH /app/node_modules/.bin:$PATH

# COPY package.json ./
# #COPY package-lock.json ./
# RUN yarn install --silent
# #RUN npm install react-scripts@3.4.1 -g --silent

# COPY . ./

# EXPOSE 3000

# CMD ["yarn", "start"]